#-------------------------------------------------------------------------------
# Copyright 2019-2020 Dominik Salvet
# github.com/dominiksalvet/vhdldep
#-------------------------------------------------------------------------------

name: CI
on: [push, pull_request]

jobs:
  Analysis:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Check shellcheck
      run: shellcheck --version

    - name: Check source files
      run: shellcheck src/vhdldep

    - name: Check install files
      run: shellcheck .install/*
